//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        public int AllowanceID { get; set; }
        public int ATID { get; set; }
        public System.DateTime WEF { get; set; }
        public int EmpTypeID { get; set; }
        public Nullable<decimal> PercOfWage { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual AllowanceTypes AllowanceTypes { get; set; }
        public virtual EmpTypes EmpTypes { get; set; }
    }
}
