//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceExceptions
    {
        public int AEID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> WEF { get; set; }
        public Nullable<int> ATID { get; set; }
        public bool Stop { get; set; }
    
        public virtual AllowanceTypes AllowanceTypes { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
