//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int EmpID { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> SysBonus { get; set; }
        public Nullable<decimal> UsrBonus { get; set; }
        public bool Frozen { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
