//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public Nullable<decimal> BonusPerc { get; set; }
        public Nullable<int> DocExpirePreWarning { get; set; }
        public int RowsPerPage { get; set; }
        public string ImageSavePath { get; set; }
        public string DefaultBank { get; set; }
    }
}
