//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditDebit
    {
        public int CreditDebitID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public int GenMonth { get; set; }
        public int GenYear { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public string Narration { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
