//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Advance = new HashSet<Advance>();
            this.Attendance = new HashSet<Attendance>();
            this.Bonus = new HashSet<Bonus>();
            this.DailyAllowance = new HashSet<DailyAllowance>();
            this.EmpDocs = new HashSet<EmpDocs>();
            this.EmploymentHistory = new HashSet<EmploymentHistory>();
            this.Loans = new HashSet<Loans>();
            this.Payroll = new HashSet<Payroll>();
            this.PayrollAllowance = new HashSet<PayrollAllowance>();
            this.PayrollRemarks = new HashSet<PayrollRemarks>();
            this.Wages = new HashSet<Wages>();
            this.CreditDebit = new HashSet<CreditDebit>();
            this.AllowanceExceptions = new HashSet<AllowanceExceptions>();
        }
    
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public int EmpTypeID { get; set; }
        public string JobTitle { get; set; }
        public string Mobile { get; set; }
        public string EmContactNo { get; set; }
        public string EmContactName { get; set; }
        public string EmContactReln { get; set; }
        public string RegBankAc { get; set; }
        public string NRegBankAc { get; set; }
        public string NRegBank { get; set; }
        public string NRegIFSC { get; set; }
        public byte BonusPayMonth { get; set; }
        public string PFno { get; set; }
        public string ESIno { get; set; }
        public string CatAB { get; set; }
        public Nullable<bool> IsHDFC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advance> Advance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonus> Bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyAllowance> DailyAllowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpDocs> EmpDocs { get; set; }
        public virtual EmpTypes EmpTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentHistory> EmploymentHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loans> Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollAllowance> PayrollAllowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollRemarks> PayrollRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wages> Wages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditDebit> CreditDebit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllowanceExceptions> AllowanceExceptions { get; set; }
    }
}
