//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentHistory
    {
        public int EHID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string ExitReason { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
