//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSkip
    {
        public int LoanSkipID { get; set; }
        public int LoanID { get; set; }
        public System.DateTime PayDate { get; set; }
        public decimal Amount { get; set; }
        public string Reason { get; set; }
    
        public virtual Loans Loans { get; set; }
    }
}
