//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loans()
        {
            this.LoanPay = new HashSet<LoanPay>();
            this.LoanSkip = new HashSet<LoanSkip>();
        }
    
        public int LoanID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime LoanDate { get; set; }
        public decimal Amount { get; set; }
        public int PayMonths { get; set; }
        public bool PaidOff { get; set; }
        public bool Default { get; set; }
        public string DefaultReason { get; set; }
        public Nullable<int> EMI { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanPay> LoanPay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanSkip> LoanSkip { get; set; }
    }
}
