//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPay
    {
        public int LoanPayID { get; set; }
        public int LoanID { get; set; }
        public int GenMonth { get; set; }
        public int GenYear { get; set; }
        public decimal Amount { get; set; }
        public bool Frozen { get; set; }
    
        public virtual Loans Loans { get; set; }
    }
}
