//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int EmpID { get; set; }
        public int GenMonth { get; set; }
        public int GenYear { get; set; }
        public Nullable<System.DateTime> GenDate { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public Nullable<int> DaysWorked { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public string LoanCmt { get; set; }
        public Nullable<decimal> AdjAmt { get; set; }
        public string AdjRemark { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool Frozen { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string Instructions { get; set; }
        public bool ExcludeExcel { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
