//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunesHR
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollRemarks
    {
        public int EmpID { get; set; }
        public int GenMonth { get; set; }
        public int GenYear { get; set; }
        public Nullable<bool> ExcludeFromExcel { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
